### ISSUE TITLE
Wrong date on input value.

### ISSUE THREAD

**Issue by MorganaUzhgorod** [Wikiki/bulma-calendar#72]
When I choose date on calendar, for example 20.06.2018, and it saved wrong date in value - 20.05.2018

This bug also present in doc. [https://wikiki.github.io/components/calendar/](https://wikiki.github.io/components/calendar/)

**Comment by andreujuanc** [comment]
I'm experiencing lots of issues regarding the last version released.

I'm some places of code base date.getMonth is used against a parsed date. Which results in a bad comparison because JS months are zero indexed.

Also if changing the date format then min and max date do not work anymore since they are hard coded.

**Comment by sertlab** [comment]
Same error here. 
Do we have any news about this?

**Comment by Wikiki** [comment]
I don't have time to fix it before thursday.

**Comment by andreujuanc** [comment]
Hi @Wikiki ,One of the things I've found is this:
 ```
  this.minDate = this.options.minDate ? this.options.minDate : '1970-01-01';
   this.maxDate = this.options.maxDate ? this.options.maxDate : '9999-12-31';
```
Where both, minDate and maxDate functions setters uses: this._dateFormat to parse the dates.
The problem arrises when user changes the dateformat (in my case at least) and '1970-01-01' gets parsed incorrectly.

Maybe those dates, should be a Date type, and so they dont get parsed. 


At show method this is commented.
```
this.date.month = this.options.startDate.getMonth();
      this.date.year = this.options.startDate.getFullYear();
      this.date.day = this.options.startDate.getDate();
```

At _renderDays method:
should use day instead of this.date, like so:
`        days += this._renderDay(day.getDate(), this.getMonth(), this.getFullYear(), isSelected, isToday, isDisabled, isEmpty, isBetween, isSelectedIn, isSelectedOut);`

Also found that _renderDay is using
`data-date="' + (year + '-' + month + '-' + day) + '"`

and then is getting the date by` this.date = e.currentTarget.dataset.date;`

Problem is that is getting set by YMD and then converted with parse, and if format does not matches YMD then it wont work.

Two solutions for this:
1) Always write data-date in the same format specified in `_dateFormat `
2) Don't parse internal dates and always use ISO or similar.

I find second options a bit simpler. And might help simplify codebase. What I mean is that all data coming into the module must be parse to ISO string using _dateFormat, and internally only ISOe format must be used. And then, data going back to the user, for example, must be given in user's `_dateFormat`.

Cheers
