### ISSUE TITLE
Events removed. 

### ISSUE THREAD

**Issue by andreujuanc** [Wikiki/bulma-calendar#73]
We need to implement events again. Ie, on Select, onclose, etc.

**Comment by Wikiki** [comment]
Sorry due to the issue with my release process the changelog has been correctly updated.

Extensions now includes a more features events management so you just have to call
```js
instance.on('datepicker:date:selected', function(datePicker){});
```

to react to an event. Each event send the datePicker instance so you are able to retrieve date.

Available events are following:
- datepicker:ready : When initialization is done
- datepicker:rendered : When all days are rendered
- datepicker:show : When datepicker is opened
- datepicker:hide : When datepicker is cloesed
- datepicker:date:selected : When user has clicked on a date

regards

**Comment by andreujuanc** [comment]
Oh! Nice, i was about to pick into the code. 
It looks great.
